name = "motion-mcp-server"
main = "src/worker.js"
compatibility_date = "2024-05-01"

[env.production]
name = "motion-mcp-server"

[env.staging]
name = "motion-mcp-server-staging"

# Environment variables (set via wrangler secret put)
# MOTION_API_KEY - Your Motion API key (required)

# Optional: Custom domain
# routes = [
#   { pattern = "mcp.yourdomain.com/*", zone_name = "yourdomain.com" }
# ]